export const serializeProduct = (product: any) => ({
  id: product._id?.toString(),
  name: product.name,
  brand: product.brand,
  collection: product.collection,
  description: product.description,
  shortDescription: product.shortDescription,
  price: product.price,
  originalPrice: product.originalPrice,
  category: product.category,
  currency: product.currency,
  features: product.features,
  specifications: product.specifications,
  images: product.images,
  inStock: product.inStock,
  stock: product.stock,
  isNew: product.isNew,
  isFeatured: product.isFeatured,
  rating: product.rating,
  reviewCount: product.reviewCount,
  tags: product.tags,
  createdAt: product.createdAt,
  updatedAt: product.updatedAt,
});

